language: java
jdk:
 - oraclejdk8

deploy:
 provider: heroku
 api_key:
  secure: 8a7b0a0a-cd49-4063-bec3-ca0bf8aded59
 app: redsocial1718v2
 on:
  repo: alexsolanero/redSocial
  branch: master
  
notifications:
  slack:
   rooms:
     - equipo1-redsocial:gHtgV5g6eQM5DkxGobKNoNIx#general
